---
title: "Final Assignment"
author: "Samantha Widman"
date: ""
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#How it Started

* Professor (Dr. Salinas) reached out to me about doing sports analytics with the baseball team
* Added 3 new people to our group

#Who Does What

* Two of the guys are working on creating 2 apps compatible with IOS and Android. 
* One app will serve as a booking mechanism for pitching data
* The other app will serve as a booking mechanism for hitting data
* Another girl and myself have used R Markdown to produce the statistics that the coaches specifically want.

#How it Works

* Once the data is collected in the app, the coach will hit submit
* The data comes to my email (haven’t figure out if this is exactly how this will work yet.. Trying to get it automated is hopeful outcome)
* The data is loaded into R Studio and is then run through the baseball statistics program. 

#Pitching Data

* http://rpubs.com/widmanst/baseball

#How This Class Has Helped

* Data Camp teaching me how to program in R
* What has helped me the most is the DPLYR package and GGPLOT2 package. 